-- AlterTable
ALTER TABLE `practicas` MODIFY `estado` ENUM('CURSANDO', 'ESPERA_INFORME_ALUMNO', 'REVISION_INFORME_ALUMNO', 'CORRECCION_INFORME_ALUMNO', 'ESPERA_INFORME_CONFIDENCIAL', 'REVISION_GENERAL', 'FINALIZADA') NOT NULL;
