-- AlterTable
ALTER TABLE `informeconfidencial` MODIFY `estado` ENUM('ENVIADA', 'REVISION', 'APROBADA', 'CORRECCION', 'DESAPROBADA', 'ESPERA') NOT NULL;

-- AlterTable
ALTER TABLE `informesalumno` MODIFY `estado` ENUM('ENVIADA', 'REVISION', 'APROBADA', 'CORRECCION', 'DESAPROBADA', 'ESPERA') NOT NULL;
